# Generated by Django 5.0.7 on 2024-07-31 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Item', max_length=200)),
                ('qtext', models.CharField(max_length=200)),
                ('jimun', models.CharField(max_length=1000)),
                ('ch1', models.CharField(max_length=200)),
                ('ch2', models.CharField(max_length=200)),
                ('ch3', models.CharField(max_length=200)),
                ('ch4', models.CharField(max_length=200)),
                ('correct_choice', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.item')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='0', max_length=100)),
                ('iscorrect', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.membership')),
            ],
        ),
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TestSheet', max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('items', models.ManyToManyField(through='kortest.Membership', to='kortest.item')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='testsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.testsheet'),
        ),
    ]
