# Generated by Django 5.0.7 on 2024-07-29 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtext', models.CharField(max_length=200)),
                ('qjimun', models.CharField(max_length=1000)),
                ('choice1', models.CharField(max_length=200)),
                ('choice2', models.CharField(max_length=200)),
                ('choice3', models.CharField(max_length=200)),
                ('choice4', models.CharField(max_length=200)),
                ('correct_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.item'),
        ),
        migrations.CreateModel(
            name='ListofAnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answersheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.answersheet')),
            ],
        ),
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.item')),
            ],
        ),
        migrations.CreateModel(
            name='ListofTestSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('testsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kortest.testsheet')),
            ],
        ),
    ]
